# Generated by Django 3.0 on 2019-12-16 20:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_auto_20191216_2103'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='isParent',
            new_name='is_parent',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='isSitter',
            new_name='is_sitter',
        ),
    ]
