# Generated by Django 3.0 on 2019-12-17 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_auto_20191216_2148'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='tarif',
            new_name='pricing',
        ),
        migrations.AlterField(
            model_name='user',
            name='schedules',
            field=models.ManyToManyField(blank=True, related_name='sitters_concerned', to='backend.Schedule'),
        ),
    ]
