# Generated by Django 3.0 on 2019-12-17 05:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_auto_20191217_0549'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='avgMark',
            new_name='avg_mark',
        ),
    ]
