# Generated by Django 3.0 on 2019-12-17 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_auto_20191217_0616'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='expired',
            field=models.BooleanField(default=False),
        ),
    ]
