# Generated by Django 3.0 on 2019-12-17 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0010_auto_20191217_0749'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='number_marks',
            field=models.IntegerField(default=0),
        ),
    ]
